name: Keep Render Services Alive

on:
  schedule:
    # Run every 10 minutes to prevent Render free tier from sleeping
    # Render services sleep after 15 minutes of inactivity
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # Prevent stuck workflows
    
    steps:
    - name: Ping WorkLog AI Backend
      run: |
        echo "🔥 Pinging WorkLog AI Backend to keep it alive..."
        
        # Ping backend health endpoint (FIXED PATH)
        backend_response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://worklog-ai-backend.onrender.com/api/health)
        
        if [ "$backend_response" -eq 200 ]; then
          echo "✅ Backend is alive (HTTP $backend_response)"
        else
          echo "⚠️ Backend responded with HTTP $backend_response"
        fi
        
        # Double-check with a lighter request to ensure service is fully warmed
        echo "✅ Backend health check completed - service should stay warm for 15+ minutes"

    - name: Verify Frontend Accessibility
      run: |
        echo "🔍 Quick frontend verification (static sites don't sleep)..."
        
        # Quick check that frontend is accessible
        frontend_response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 https://worklog.ajkaysolutions.com)
        
        if [ "$frontend_response" -eq 200 ]; then
          echo "✅ Frontend is accessible (HTTP $frontend_response)"
        else
          echo "⚠️ Frontend check: HTTP $frontend_response"
        fi

    - name: Summary
      run: |
        echo "🎯 Keep-alive ping completed at $(date)"
        echo "📊 This prevents Render free tier services from sleeping"
        echo "⏰ Next ping scheduled in 10 minutes"